### PR TITLE
data seeded - postcode issue needs looking into

### PR DESCRIPTION
**Pull request by mayhemcreates**
- Added Faker gem 
image

- Added the seeds - however, not sure if I've set the locale correctly for Faker as it's still pulling through non-uk postcodes. 
image

- it might look like some changes in the models, but I was testing some things - nothing should have changed....

### CODE REVIEW

**Comment by chungus84** [comment]
So to set the locale of Faker you can call Faker::Config.locale = "en-GB". So the attached screenshot gives me 5 randomly generated postcodes:
O1 1FQ
GO1 8BN
R5B 3BU
UC8 1NL
W3E 3LA

Screenshot 2022-08-04 at 13 32 36

However they are not actual postcodes according to this Stackoverflow thread
https://stackoverflow.com/questions/51592639/does-faker-generate-real-uk-postcodes#:~:text=The%20postcodes%20that%20faker%20generates,actual%20place%20in%20the%20UK.

But at we can set the locale

**Comment by chungus84** [comment]
But we can use [Postcode](https://postcodes.io/) api which will give us a genuine postcode (from what I have seen)
you just need to require both open-uri & json


and replace the line 
postcode: Faker::Address.posctode 
with 
postcode: JSON.parse(URI.open('https://api.postcodes.io/random/postcodes').read)["result"]["postcode"]

**Comment by mayhemcreates** [comment]
I've changed to the postcode api on the latest commit.

**Comment by chungus84** [comment]
Looks good

**Pull request merged**
